version: "3.9"

services:
  db:
    image: postgres:15
    container_name: historical-db
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: historical_data
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  minio:
    image: minio/minio
    container_name: historical-minio
    restart: always
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_data:/data
    command: server --console-address ":9001" /data

  fastapi:
    build: .
    container_name: historical-api
    restart: always
    depends_on:
      - db
      - minio
    environment:
      DATABASE_URL: postgresql+asyncpg://admin:password@db/historical_data
      MINIO_ENDPOINT: http://minio:9000
      MINIO_ACCESS_KEY: minioadmin
      MINIO_SECRET_KEY: minioadmin
      BUCKET_NAME: historical-files
    ports:
      - "8000:8000"

volumes:
  postgres_data:
  minio_data:
